### ISSUE TITLE
error because of wrong file name?

### ISSUE THREAD

**Issue by JanOdijk** [proycon/alpino_clam_webservice#1]
In project 
https://webservices.cls.ru.nl/alpino/1130/
an error is reported, perhaps because of  the fact that the filename 1130.txt is not OK?

Relevant part of the log file: (https://webservices.cls.ru.nl/alpino/1130/output/error.log )

**** parsed 3 (line number 3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/alpino_webservice/alpino_wrapper.py", line 102, in <module>
    doc = alpino2folia.makefoliadoc(foliafile)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/foliatools/alpino2folia.py", line 55, in makefoliadoc
    foliadoc = folia.Document(id=baseid, processor=processor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/folia/main.py", line 7397, in __init__
    isncname(kwargs['id'])
  File "/usr/local/lib/python3.11/dist-packages/folia/main.py", line 9296, in isncname
    raise ValueError('Invalid XML NCName identifier: ' + name + ' (at position ' + str(i+1)+')')
ValueError: Invalid XML NCName identifier: 1130.txt (at position 1)
[CLAM Dispatcher] Process ended (2023-12-01 10:57:43, 6.50318s)

**Comment by proycon** [comment]
Indeed, filenames with only numerals are problematic as that is not a usable identifier for the XML (FoLiA) output. If you rename your files to start with an alphabetic character then it should be okay.

**Comment by sanmai-NL** [comment]
@proycon Where is that `folia` package on GitHub? I propose to sanitize the identifier automatically.

**Comment by proycon** [comment]
It's https://github.com/proycon/foliapy, but this is mediated via the alpino2folia converter in  https://github.com/proycon/foliatools, I'll solve it on that level.

**Comment by proycon** [comment]
Implemented, will deploy later tonight/tomorrow
